import React from 'react'
import { View, Text } from 'react-native'
import PropTypes from 'prop-types'

import styles from './styles'

const SampleScreen = ({ text }) => {
  return (
    <View style={styles.container}>
      <Text>{text}</Text>
    </View>
  )
}

const { string } = PropTypes

SampleScreen.propTypes = {
  text: string,
}

SampleScreen.defaultProps = {
  text: 'This Screen is generated by react-native-template.',
}

export default SampleScreen
