import React from 'react'
import { Text, View } from 'react-native'
import PropTypes from 'prop-types'

import styles from './styles'

const {{ properCase name }}Component = ({ text }) => {
  return (
    <View style={styles.container}>
      <Text>{text}</Text>
    </View>
  )
}

const { string } = PropTypes

{{ properCase name }}Component.propTypes = {
  text: string,
}

{{ properCase name }}Component.defaultProps = {
  text: 'This component is generated by react-native-template.',
}

export default {{ properCase name }}Component
