import React, { useState } from 'react';
import { Text, View } from 'react-native';
import styles from './styles';

function ComponentName(props) {
  const [count, setCount] = useState(0);

  return (
    <View style={styles.container}>
      <Text>This component is generated by react-native-template.</Text>
    </View>
  )
}
export default ComponentName;
