import React from 'react'
import PropTypes from 'prop-types'

import View from './view'
import styles from './styles'

const {{ properCase name }}Screen = ({ text }) => {
  return (
    <View />
  )
}

const { string } = PropTypes

{{ properCase name }}Screen.propTypes = {
  text: string,
}

{{ properCase name }}Screen.defaultProps = {
  text: 'This Screen is generated by react-native-template.',
}

export default {{ properCase name }}Screen
