import React from 'react';
import { View } from 'react-native';
import styles from './styles';

class ScreenName extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>This Screen is generated by react-native-template.</Text>
      </View>
    );
  }
}

export default ScreenName