import React from 'react'
import { View, Text } from 'react-native'
import PropTypes from 'prop-types'

import styles from './styles'

const {{ properCase name }}View = ({ text }) => {
  return (
    <View style={styles.container}>
      <Text>{text}</Text>
    </View>
  )
}

const { string } = PropTypes

{{ properCase name }}View.propTypes = {
  text: string,
}

{{ properCase name }}View.defaultProps = {
  text: 'This View is generated by react-native-template.',
}

export default {{ properCase name }}View
